apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2024-07-31T07:14:23Z'
  generation: 2
  labels:
    app: jx-api-materials-product-status
  name: jx-api-materials-product-status-tuanzhang
  namespace: cx-spider
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jx-api-materials-product-status
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 80%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jx-api-materials-product-status
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: spider-tag
                    operator: In
                    values:
                      - cx-task
      containers:
        - command:
            - ./spider
            - jx-api/materials-product-status
          env:
            - name: DOT_SPIDER_WORKER_NUM
              value: '10'
            - name: DOT_KAFKA_BOOTSTRAP_SERVERS
              value: 10.64.124.198:9092,10.64.124.197:9092,10.64.124.199:9092
            - name: aliyun_logs_cx-spider
              value: stdout
            - name: API_ACCOUNT
              value: tuanzhang
            - name: API_ACCOUNT_DETAIL
              value: tuanzhang
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/cmm-crawler/cx-spider:master'
          imagePullPolicy: Always
          name: jx-api-materials-product-status
          resources:
            requests:
              cpu: 32m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
        - hostPath:
            path: /data
            type: ''
          name: volume-data
